services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
            POSTGRES_DB: smdb
        ports:
            - "5432:5432"
